Repository Collab4exaNBody/exaNBody, pull requests merged in 2025-07, with the labels that each got.

#100 fix default value in reduce_cell_particles
  src/compute/include/exanb/compute/reduce_cell_particles.h
Labels: bug

#105 104 remove noise from lattice
  src/compute/include/exanb/compute/gaussian_noise.h
  src/compute/include/exanb/compute/uniform_noise.h
  src/compute/uniform_noise.cpp
  src/grid_cell_particles/include/exanb/grid_cell_particles/bulk_generator.h
  src/grid_cell_particles/include/exanb/grid_cell_particles/generate_particle_lattice.h
  src/grid_cell_particles/include/exanb/grid_cell_particles/lattice_generator.h
  src/grid_cell_particles/include/exanb/grid_cell_particles/legacy_lattice_generator.h
Labels: documentation, feature, add_opertor

#106 87 add error messages in lattice
  contribs/microStamp/samples/slicing_test.msp
  src/grid_cell_particles/include/exanb/grid_cell_particles/bulk_generator.h
  src/grid_cell_particles/include/exanb/grid_cell_particles/lattice_generator.h
  src/grid_cell_particles/include/exanb/grid_cell_particles/legacy_lattice_generator.h
Labels: documentation
